-- INSERT INTO user_info
-- VALUES (1, 'email@bk.ru', 'password', 'ROLE_USER');
-- INSERT INTO user_info
-- VALUES (2, 'email2@bk.ru', 'password2', 'ROLE_USER');
-- INSERT INTO categories
-- values (1, 'Телевизеры', 1);
-- INSERT INTO categories
-- values (2, 'Коньтютеры', 2);
-- INSERT INTO categories
-- values (3, 'Телефоны', 3);
-- INSERT INTO categories
-- values (4, 'Собаки', 4);
-- INSERT INTO categories
-- values (5, 'Кошки', 5);
-- INSERT INTO categories
-- values (6, 'Деревья', 6);
-- INSERT INTO categories
-- values (7, 'Стиральная машина', 7);
-- INSERT INTO categories
-- values (8, 'Просто машина', 8);