DROP table IF EXISTS payments CASCADE;
DROP table IF EXISTS users CASCADE;
DROP table IF EXISTS authorities CASCADE;
DROP table IF EXISTS addresses CASCADE;
DROP table IF EXISTS stocks CASCADE;
DROP table IF EXISTS categories CASCADE;
DROP table IF EXISTS attributes CASCADE;
DROP table IF EXISTS category_attributes CASCADE;
DROP table IF EXISTS models CASCADE;
DROP table IF EXISTS model_images CASCADE;
DROP table IF EXISTS model_attributes CASCADE;
DROP table IF EXISTS sales CASCADE;
DROP table IF EXISTS collections CASCADE;
DROP table IF EXISTS model_collection_join CASCADE;
DROP table IF EXISTS user_favourites CASCADE;
DROP table IF EXISTS baskets CASCADE;
DROP table IF EXISTS model_sets CASCADE;
DROP table IF EXISTS products CASCADE;
DROP table IF EXISTS orders CASCADE;
DROP table IF EXISTS deliveries CASCADE;

CREATE TABLE IF NOT EXISTS payments (
     payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     completed TIMESTAMP,
     status VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(250) UNIQUE NOT NULL,
    email varchar(250) UNIQUE NOT NULL,
    password varchar(250) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    first_name varchar(250),
    last_name varchar(250),
    phone varchar(250)
    );

CREATE TABLE IF NOT EXISTS authorities (
    authority_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority varchar(15)
    );

DROP TABLE IF EXISTS users_authorities CASCADE;
CREATE TABLE IF NOT EXISTS users_authorities (
    user_id BIGINT,
    authority_id BIGINT,
    CONSTRAINT fk_authority_id FOREIGN KEY (authority_id) REFERENCES authorities (authority_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (user_id)
    );

CREATE TABLE IF NOT EXISTS addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE RESTRICT NOT NULL,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    house_number BIGINT NOT NULL,
    flat_number BIGINT NOT NULL,
    entrance_number BIGINT NOT NULL,
    floor_number BIGINT NOT NULL,
    comment VARCHAR(500)
    );

CREATE TABLE IF NOT EXISTS stocks (
    stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_id BIGINT REFERENCES addresses(address_id) NOT NULL
    );

CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    parent_category_id BIGINT REFERENCES categories(category_id)
    );

INSERT INTO categories values (1, 'Телевизеры', 1);
INSERT INTO categories values (2, 'Коньтютеры', 2);
INSERT INTO categories values (3, 'Телефоны', 3);
INSERT INTO categories values (4, 'Собаки', 4);
INSERT INTO categories values (5, 'Кошки', 5);
INSERT INTO categories values (6, 'Деревья', 6);
INSERT INTO categories values (7, 'Стиральная машина', 7);
INSERT INTO categories values (8, 'Просто машина', 8);

CREATE TABLE IF NOT EXISTS attributes (
    attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS category_attributes (
    category_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(category_id) ON DELETE CASCADE NOT NULL ,
    attribute_id BIGINT REFERENCES attributes(attribute_id) ON DELETE CASCADE NOT NULL ,
    priority BIGINT NOT NULL,
    type VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS models (
    model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    price BIGINT NOT NULL,
    category_id BIGINT REFERENCES categories(category_id) ON DELETE RESTRICT NOT NULL,
    status VARCHAR(100)
    );

CREATE TABLE IF NOT EXISTS model_images (
    model_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT REFERENCES models(model_id) NOT NULL,
    image_link VARCHAR(200) NOT NULL
    );

CREATE TABLE IF NOT EXISTS model_attributes (
    model_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT REFERENCES models(model_id) ON DELETE CASCADE NOT NULL,
    valueses varchar(250) NOT NULL,
    category_attribute_id BIGINT REFERENCES category_attributes(category_attribute_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS sales (
    sale_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT REFERENCES models(model_id) NOT NULL,
    percent INT NOT NULL
    );

CREATE TABLE IF NOT EXISTS collections (
    collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    image_link VARCHAR(200) NOT NULL
    );

CREATE TABLE IF NOT EXISTS model_collection_join (
    model_id BIGINT REFERENCES models(model_id) ON DELETE CASCADE NOT NULL,
    collection_id BIGINT REFERENCES collections(collection_id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (model_id, collection_id)
    );

CREATE TABLE IF NOT EXISTS user_favourites (
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    model_id BIGINT REFERENCES models(model_id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (user_id, model_id)
    );

CREATE TABLE IF NOT EXISTS baskets (
    basket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE RESTRICT NOT NULL,
    created TIMESTAMP NOT NULL,
    status VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS model_sets (
    model_set_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT REFERENCES models(model_id) ON DELETE RESTRICT NOT NULL,
    count INT NOT NULL,
    basket_id BIGINT REFERENCES baskets(basket_id) ON DELETE RESTRICT,
    stock_id BIGINT REFERENCES stocks(stock_id) ON DELETE RESTRICT,
    type VARCHAR(100)
    );

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR(100) NOT NULL,
    model_id BIGINT REFERENCES models(model_id) ON DELETE RESTRICT NOT NULL,
    model_set_id BIGINT REFERENCES model_sets(model_set_id) ON DELETE RESTRICT NOT NULL,
    status VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    basket_id BIGINT REFERENCES baskets(basket_id) ON DELETE RESTRICT NOT NULL,
    payment_id BIGINT REFERENCES payments(payment_id) ON DELETE RESTRICT,
    address_id BIGINT REFERENCES addresses(address_id) ON DELETE RESTRICT NOT NULL,
    created TIMESTAMP NOT NULL,
    final_price BIGINT,
    status VARCHAR(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS deliveries (
    delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(order_id) ON DELETE RESTRICT NOT NULL,
    stock_id BIGINT REFERENCES stocks(stock_id) NOT NULL,
    status VARCHAR(100)
    );